BackBundle\Entity\Stade:
    type: entity
    table: null
    repositoryClass: BackBundle\Repository\StadeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        lieu:
            type: string
            length: 255
    oneToMany:
        event:
            targetEntity: Event
            mappedBy: stade

    lifecycleCallbacks: {  }
