BackBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: BackBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            nullable : true
        lastName:
            type: string
            length: 255
            nullable : true
        Adresse:
            type: text
    manyToMany:
        tickets:
            targetEntity: Tickets
            inversedBy: users
            joinTable:
                name: commande
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tickets_id:
                        referencedColumnName: id

Tickets:
    type: entity
    manyToMany:
        users:
            targetEntity: User
            mappedBy: tickets
    lifecycleCallbacks: {  }
