<?php

namespace BackBundle\Repository;

/**
 * StadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StadeRepository extends \Doctrine\ORM\EntityRepository
{
}
